services:
  ruciodb:
    extends:
      file: docker-compose.yml
      service: ruciodb
  rucio:
    extends:
      file: docker-compose.yml
      service: rucio
    depends_on:
      - ruciodb
    image: docker.io/rucio/rucio-dev:${RUCIO_IMG}
    environment:
      - RUCIO_ENABLE_LOGS=True
    volumes:
      - /tmp/rucio_logs:/var/log/httpd
  rucio-jupyterlab:
    image: "rucio-jupyterlab"
    build:
      context: .
    profiles:
      - extension
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_rucio.pem:/etc/grid-security/hostcert.pem:z
      - ../../certs/hostcert_rucio.key.pem:/etc/grid-security/hostkey.pem:z
      - ../../certs/rucio_ca.pem:/opt/rucio/etc/rucio_ca.pem:z
      - ../../certs/ruciouser.pem:/opt/rucio/etc/usercert.pem:z
      - ../../certs/ruciouser.key.pem:/opt/rucio/etc/userkey.pem:z
      - ../../../../../..:/rucio-jupyterlab:Z
      - /tmp/rucio_xrd1:/tmp/rucio_xird1:z
      - ../../../../token.json:/tmp/rucio_token.json
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RUCIO_CA_CERT=/opt/rucio/etc/rucio_ca.pem
      - RUCIO_MODE=replica
      - RUCIO_WILDCARD_ENABLED=1
      - RUCIO_BASE_URL=https://rucio
      - RUCIO_AUTH_URL=https://rucio
      - RUCIO_DESTINATION_RSE=XRD1
      - RUCIO_DISPLAY_NAME=Rucio Test
      - RUCIO_NAME=rucio.test
      - RUCIO_PATH_BEGINS_AT=1
      - RUCIO_RSE_MOUNT_PATH=/tmp/rucio_xrd1
      - CONTAINER_PURPOSE=develop
      - RUCIO_OIDC_AUTH=file
      - RUCIO_OIDC_FILE_NAME=/tmp/rucio_token.json
    ports:
      - "8888:8888"
  xrd1:
    image: docker.io/rucio/test-xrootd
    extends:
      file: docker-compose.yml
      service: xrd1
    volumes:
      - /tmp/rucio_xrd1:/rucio:z
  xrd2:
    image: docker.io/rucio/test-xrootd
    extends:
      file: docker-compose.yml
      service: xrd2
  xrd3:
    image: docker.io/rucio/test-xrootd
    extends:
      file: docker-compose.yml
      service: xrd3
  xrd4:
    image: docker.io/rucio/test-xrootd
    extends:
      file: docker-compose.yml
      service: xrd4
  indigoiam-login-service:
    extends:
      file: docker-compose.yml
      service: indigoiam-login-service
    volumes:
      - ../../../../iam_config.yml:/indigo-iam/config/config.yml:Z
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ../../../../nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../certs/hostcert_keycloak.pem:/etc/nginx/certs/keycloak.crt:z
      - ../../certs/hostcert_keycloak.key.pem:/etc/nginx/certs/keycloak.key:z
      - ../../../../dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - ../../certs/hostcert_indigoiam.pem:/etc/nginx/certs/indigoiam.pem:z
      - ../../certs/hostcert_indigoiam.key.pem:/etc/nginx/certs/indigoiam.key:z
      - ../../certs/hostcert_rucio.pem:/etc/nginx/certs/rucio.pem:z
      - ../../certs/hostcert_rucio.key.pem:/etc/nginx/certs/rucio.key:z

    
